package: jobs
version: '1.1.0'
author: FriendsOfREDAXO

page:
    title: 'translate:jobs_title'
    perm: 'jobs[]'
    icon: rex-icon fa-users
    subpages:
        jobs: { title: 'translate:jobs_jobs', icon: rex-icon fa-users }
        category: { title: 'translate:d2u_helper_category', icon: rex-icon rex-icon-open-category }
        contact: { title: 'translate:jobs_contacts', icon: rex-icon rex-icon-user, perm: 'jobs[edit_data]' }
        hr4you_import: { title: 'translate:jobs_hr4you', icon: rex-icon rex-icon-user, perm: 'jobs[hr4you]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'jobs[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'jobs[settings]' }

requires:
    redaxo: '>=5.16.0'
    packages:
        d2u_helper: '>=1.14.0'
        sprog: '>=1.0.0'
        url: '>=2.0'
        yrewrite: '>=2.0.1'
    php: '>=8.0'

default_config:
    hr4you_headline_tag: 'h3'
    use_hr4you: false

installer_ignore:
    - .github